/*****************************************************************************
*
* Copyright (c) 2000 - 2016, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtGOTHIC_snpFileFormat.C                           //
// ************************************************************************* //

#include <avtGOTHIC_snpFileFormat.h>

#include <string>

#include <vtkCellType.h>
#include <vtkUnsignedLongArray.h>
#include <vtkDoubleArray.h>
#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>

#include <InvalidVariableException.h>

// to use ostringstream
#include <iostream>

//-------------------------------------------------------------------------
// HDF5 related original routines
//-------------------------------------------------------------------------
#include <hdf5.h>
//-------------------------------------------------------------------------
#define chkHDF5err(err) __chkHDF5err(err, __FILE__, __LINE__)
//-------------------------------------------------------------------------
#define __FPRINTF__(dst, ...)				\
  {								\
    fprintf(dst, "%s(%d): %s\n", __FILE__, __LINE__, __func__);	\
    fprintf(dst, ##__VA_ARGS__);				\
    fflush(NULL);						\
  }
//-------------------------------------------------------------------------
#if defined(MPI_INCLUDED) || defined(OMPI_MPI_H)
#     define __KILL__(dst, ...)		\
  {						\
    __FPRINTF__(dst, ##__VA_ARGS__);		\
    MPI_Abort(MPI_COMM_WORLD, 1);		\
  }
#else
#     define __KILL__(dst, ...)		\
  {						\
    __FPRINTF__(dst, ##__VA_ARGS__);		\
    exit(EXIT_FAILURE);				\
  }
#endif
//-------------------------------------------------------------------------
void __chkHDF5err(herr_t err, const char *file, const int line)
{
  //-----------------------------------------------------------------------
  /* Returns a non-negative value if successful; otherwise returns a negative value. */
  if( err < 0 ){
    fprintf(stderr, "Error is detected at %s(%d)\n", file, line);
    __KILL__(stderr, "HDF5 error, error ID is %d\n", err);
  }/* if( err < 0 ){ */
  //-----------------------------------------------------------------------
}
//-------------------------------------------------------------------------
typedef unsigned long int ulong;
//-------------------------------------------------------------------------


using     std::string;


// ****************************************************************************
//  Method: avtGOTHIC_snpFileFormat constructor
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Mon Nov 14 19:45:14 PST 2016
//
// ****************************************************************************

avtGOTHIC_snpFileFormat::avtGOTHIC_snpFileFormat(const char *filename)
    : avtSTSDFileFormat(filename)
{
    // INITIALIZE DATA MEMBERS
}


// ****************************************************************************
//  Method: avtGOTHIC_snpFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Mon Nov 14 19:45:14 PST 2016
//
// ****************************************************************************

void
avtGOTHIC_snpFileFormat::FreeUpResources(void)
{
}


// ****************************************************************************
//  Method: avtGOTHIC_snpFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Mon Nov 14 19:45:14 PST 2016
//
// ****************************************************************************

void
avtGOTHIC_snpFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);
  hid_t group = H5Gopen(target, "unit system/axis labels", H5P_DEFAULT);
  // read unit name contained in the file (written as an attribute)
  hid_t str4format = H5Tcopy(H5T_C_S1);
  const int charSize = 16;
  chkHDF5err(H5Tset_size(str4format, charSize));
  char length_unit[charSize], velocity_unit[charSize], accel_unit[charSize], senergy_unit[charSize];
  hid_t attribute;
  attribute = H5Aopen(group,   "length_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,   length_unit));  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(group, "velocity_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format, velocity_unit));  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(group,    "accel_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,    accel_unit));  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(group,  "senergy_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,  senergy_unit));  chkHDF5err(H5Aclose(attribute));
  chkHDF5err(H5Tclose(str4format));
  // close the target file
  chkHDF5err(H5Gclose(group));
  chkHDF5err(H5Fclose(target));

  string meshname = "snp";
  // add point mesh
  avtMeshMetaData *mmd = new avtMeshMetaData;
  mmd->name = meshname;
  mmd->spatialDimension = 3;
  mmd->topologicalDimension = 0;
  mmd->meshType = AVT_POINT_MESH;
  mmd->numBlocks = 1;  // <-- this must be 1 for STSD
  mmd->xLabel = "x";  mmd->xUnits = length_unit;
  mmd->yLabel = "y";  mmd->yUnits = length_unit;
  mmd->zLabel = "z";  mmd->zUnits = length_unit;
  md->Add(mmd);

  // add physical variables
  std::ostringstream var;
  // add scalar variables
  avtScalarMetaData *pot = new avtScalarMetaData;  pot->meshName = meshname;  pot->centering = AVT_NODECENT;  pot->hasUnits =  true;
  avtScalarMetaData *idx = new avtScalarMetaData;  idx->meshName = meshname;  idx->centering = AVT_NODECENT;  idx->hasUnits = false;
  var << meshname << "/potential";  pot->name = var.str();  pot->units = senergy_unit;  md->Add(pot);  var.str("");
  var << meshname << "/index"    ;  idx->name = var.str();                              md->Add(idx);  var.str("");
  // add vector variables
  avtVectorMetaData *acc = new avtVectorMetaData;  acc->meshName = meshname;  acc->centering = AVT_NODECENT;  acc->hasUnits = true;  acc->varDim = 3;
  avtVectorMetaData *vel = new avtVectorMetaData;  vel->meshName = meshname;  vel->centering = AVT_NODECENT;  vel->hasUnits = true;  vel->varDim = 3;
  var << meshname << "/acceleration";  acc->name = var.str();  acc->units =    accel_unit;  md->Add(acc);  var.str("");
  var << meshname << "/velocity"    ;  vel->name = var.str();  vel->units = velocity_unit;  md->Add(vel);  var.str("");
}


// ****************************************************************************
//  Method: avtGOTHIC_snpFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Mon Nov 14 19:45:14 PST 2016
//
// ****************************************************************************

vtkDataSet *
avtGOTHIC_snpFileFormat::GetMesh(const char *meshname)
{
  if( strcmp("snp", meshname) == 0 ){
    // open the target file
    const char* filename = GetFilename();
    hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

    // read conversion factor
    hid_t group = H5Gopen(target, "unit system/conversion factors", H5P_DEFAULT);
    double length2astro;
    hid_t attribute = H5Aopen(group, "length2astro", H5P_DEFAULT);
    chkHDF5err(H5Aread(attribute, H5T_NATIVE_DOUBLE, &length2astro));
    chkHDF5err(H5Aclose(attribute));
    chkHDF5err(H5Gclose(group));

    // read useDP
    int useDP;
    group = H5Gopen(target, meshname, H5P_DEFAULT);
    attribute = H5Aopen(group, "useDP", H5P_DEFAULT);
    chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &useDP));
    chkHDF5err(H5Aclose(attribute));

    const int ndims = 3;
    ulong num;
    // read number of nodes from the file (written as an attribute)
    attribute = H5Aopen(group, "number", H5P_DEFAULT);
    chkHDF5err(H5Aread(attribute, H5T_NATIVE_ULONG, &num));
    chkHDF5err(H5Aclose(attribute));
    int nnodes = (int)num;

    if( useDP == 0 ){
      // read the XYZ coordinates from the file
      float *position = new float[nnodes * ndims];
      hid_t dataset = H5Dopen(group, "position", H5P_DEFAULT);
      chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, position));
      chkHDF5err(H5Dclose(dataset));

      // close the target file
      chkHDF5err(H5Gclose(group));
      chkHDF5err(H5Fclose(target));

      // create the vtkPoints object and copy points into it
      vtkPoints *points = vtkPoints::New();
      points->SetNumberOfPoints(nnodes);
      float *pts = (float *)points->GetVoidPointer(0);
      for(int ii = 0; ii < ndims * nnodes; ii++)
	pts[ii] = (float)((double)position[ii] * length2astro);

      // create a vtkUnstructuredGrid to contain the point cells
      vtkUnstructuredGrid *ugrid = vtkUnstructuredGrid::New();
      ugrid->SetPoints(points);
      points->Delete();
      ugrid->Allocate(nnodes);
      vtkIdType onevertex;
      for(int ii = 0; ii < nnodes; ii++){
	onevertex = ii;
	ugrid->InsertNextCell(VTK_VERTEX, 1, &onevertex);
      }// for(int ii = 0; ii < nnodes; ii++){
      delete [] position;

      return ugrid;
    }// if( useDP == 0 ){
    else{
      // read the XYZ coordinates from the file
      double *position = new double[nnodes * ndims];
      hid_t dataset = H5Dopen(group, "position", H5P_DEFAULT);
      chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, position));
      chkHDF5err(H5Dclose(dataset));

      // close the target file
      chkHDF5err(H5Gclose(group));
      chkHDF5err(H5Fclose(target));

      // create the vtkPoints object and copy points into it
      vtkPoints *points = vtkPoints::New();
      points->SetNumberOfPoints(nnodes);
      double *pts = (double *)points->GetVoidPointer(0);
      for(int ii = 0; ii < ndims * nnodes; ii++)
	pts[ii] = position[ii] * length2astro;

      // create a vtkUnstructuredGrid to contain the point cells
      vtkUnstructuredGrid *ugrid = vtkUnstructuredGrid::New();
      ugrid->SetPoints(points);
      points->Delete();
      ugrid->Allocate(nnodes);
      vtkIdType onevertex;
      for(int ii = 0; ii < nnodes; ii++){
	onevertex = ii;
	ugrid->InsertNextCell(VTK_VERTEX, 1, &onevertex);
      }// for(int ii = 0; ii < nnodes; ii++){
      delete [] position;

      return ugrid;
    }// else{
  }// if( strncmp("data", meshname, 4) == 0 ){
  else{
    // Error exception
    EXCEPTION1(InvalidVariableException, meshname);
  }// else{
}


// ****************************************************************************
//  Method: avtGOTHIC_snpFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Mon Nov 14 19:45:14 PST 2016
//
// ****************************************************************************

vtkDataArray *
avtGOTHIC_snpFileFormat::GetVar(const char *varname)
{
  // extract meshname and variable from varname (varname = meshname/variable)
  const string str = varname;
  string::size_type pos = str.find_last_of("/");
  string meshname = str.substr(0, pos);
  string variable = str.substr(pos + 1, str.size() - pos);

  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

  ulong ulnum;
  // read number of particles from the file (written as an attribute)
  hid_t group = H5Gopen(target, meshname.c_str(), H5P_DEFAULT);
  hid_t attribute = H5Aopen(group, "number", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_ULONG, &ulnum));
  chkHDF5err(H5Aclose(attribute));
  int num = (int)ulnum;

  // read useDP
  int useDP;
  attribute = H5Aopen(group, "useDP", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &useDP));
  chkHDF5err(H5Aclose(attribute));

  if( strcmp(variable.c_str(), "index") != 0 ){
    if( useDP == 0 ){
      // read the target variable (physical quantities)
      float *array = new float[num];
      hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
      chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, array));
      chkHDF5err(H5Dclose(dataset));
      chkHDF5err(H5Gclose(group));

      // read conversion factor
      group = H5Gopen(target, "unit system/conversion factors", H5P_DEFAULT);
      double factor = 0.0;
      string dimension;
      if( strcmp(variable.c_str(), "potential") == 0 )      dimension = "senergy2astro";
      hid_t attribute = H5Aopen(group, dimension.c_str(), H5P_DEFAULT);
      chkHDF5err(H5Aread(attribute, H5T_NATIVE_DOUBLE, &factor));
      chkHDF5err(H5Aclose(attribute));
      chkHDF5err(H5Gclose(group));

      // close the target file
      chkHDF5err(H5Fclose(target));

      vtkFloatArray *rv = vtkFloatArray::New();
      rv->SetNumberOfTuples(num);
      for(int ii = 0; ii < num; ii++)
	rv->SetTuple1(ii, (float)((double)array[ii] * factor));

      // delete temporary arrays
      delete [] array;

      return rv;
    }// if( useDP == 0 ){
    else{
      // read the target variable (physical quantities)
      double *array = new double[num];
      hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
      chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, array));
      chkHDF5err(H5Dclose(dataset));
      chkHDF5err(H5Gclose(group));

      // read conversion factor
      group = H5Gopen(target, "unit system/conversion factors", H5P_DEFAULT);
      double factor = 0.0;
      string dimension;
      if( strcmp(variable.c_str(), "potential") == 0 )      dimension = "senergy2astro";
      hid_t attribute = H5Aopen(group, dimension.c_str(), H5P_DEFAULT);
      chkHDF5err(H5Aread(attribute, H5T_NATIVE_DOUBLE, &factor));
      chkHDF5err(H5Aclose(attribute));
      chkHDF5err(H5Gclose(group));

      // close the target file
      chkHDF5err(H5Fclose(target));

      vtkDoubleArray *rv = vtkDoubleArray::New();
      rv->SetNumberOfTuples(num);
      for(int ii = 0; ii < num; ii++)
	rv->SetTuple1(ii, array[ii] * factor);

      // delete temporary arrays
      delete [] array;

      return rv;
    }// else{
  }// if( strcmp(variable.c_str(), "index") != 0 ){
  else{
    // read the target variable (index)
    ulong *array = new ulong[num];
    hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_ULONG, H5S_ALL, H5S_ALL, H5P_DEFAULT, array));
    chkHDF5err(H5Dclose(dataset));

    // close the target file
    chkHDF5err(H5Gclose(group));
    chkHDF5err(H5Fclose(target));

    vtkUnsignedLongArray *rv = vtkUnsignedLongArray::New();
    rv->SetNumberOfTuples(num);
    for(int ii = 0; ii < num; ii++)
      rv->SetTuple1(ii, array[ii]);

    // delete temporary arrays
    delete [] array;

    return rv;
  }// else{
}


// ****************************************************************************
//  Method: avtGOTHIC_snpFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Mon Nov 14 19:45:14 PST 2016
//
// ****************************************************************************

vtkDataArray *
avtGOTHIC_snpFileFormat::GetVectorVar(const char *varname)
{
  // extract meshname and variable from varname (varname = meshname/variable)
  const string str = varname;
  string::size_type pos = str.find_last_of("/");
  string meshname = str.substr(0, pos);
  string variable = str.substr(pos + 1, str.size() - pos);

  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

  // read conversion factor
  hid_t group = H5Gopen(target, "unit system/conversion factors", H5P_DEFAULT);
  double factor = 0.0;
  string dimension;
  if( strcmp(variable.c_str(),     "velocity") == 0 )    dimension = "velocity2astro";
  if( strcmp(variable.c_str(), "acceleration") == 0 )    dimension =    "accel2astro";
  hid_t attribute = H5Aopen(group, dimension.c_str(), H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_DOUBLE, &factor));
  chkHDF5err(H5Aclose(attribute));
  chkHDF5err(H5Gclose(group));

  ulong ulnum;
  // read number of particles from the file (written as an attribute)
  group = H5Gopen(target, meshname.c_str(), H5P_DEFAULT);
  attribute = H5Aopen(group, "number", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_ULONG, &ulnum));
  chkHDF5err(H5Aclose(attribute));
  int num = (int)ulnum;
  const int ndims = 3;

  // read useDP
  int useDP;
  attribute = H5Aopen(group, "useDP", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &useDP));
  chkHDF5err(H5Aclose(attribute));

  if( useDP == 0 ){
    // read the target variable
    float *array = new float[num * ndims];
    hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, array));
    chkHDF5err(H5Dclose(dataset));
    chkHDF5err(H5Gclose(group));

    // close the target file
    chkHDF5err(H5Fclose(target));

    vtkFloatArray *rv = vtkFloatArray::New();
    rv->SetNumberOfComponents(ndims);
    rv->SetNumberOfTuples(num);
    float *dat = (float *)rv->GetVoidPointer(0);
    for(int ii = 0; ii < ndims * num; ii++)
      dat[ii] = (float)((double)array[ii] * factor);

    // delete temporary arrays
    delete [] array;

    return rv;
  }// if( useDP == 0 ){
  else{
    // read the target variable
    double *array = new double[num * ndims];
    hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, array));
    chkHDF5err(H5Dclose(dataset));
    chkHDF5err(H5Gclose(group));

    // close the target file
    chkHDF5err(H5Fclose(target));

    vtkDoubleArray *rv = vtkDoubleArray::New();
    rv->SetNumberOfComponents(ndims);
    rv->SetNumberOfTuples(num);
    double *dat = (double *)rv->GetVoidPointer(0);
    for(int ii = 0; ii < ndims * num; ii++)
      dat[ii] = array[ii] * factor;

    // delete temporary arrays
    delete [] array;

    return rv;
  }// else{
}


// optional function(s)
double
avtGOTHIC_snpFileFormat::GetTime(void)
{
  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

  // read current time contained in the file (written as an attribute)
  double dtime;
  hid_t group = H5Gopen(target, "snp", H5P_DEFAULT);
  hid_t attribute = H5Aopen(group, "time", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_DOUBLE, &dtime));
  chkHDF5err(H5Aclose(attribute));
  chkHDF5err(H5Gclose(group));

  // read conversion factor
  group = H5Gopen(target, "unit system/conversion factors", H5P_DEFAULT);
  double factor = 0.0;
  attribute = H5Aopen(group, "time2astro", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_DOUBLE, &factor));
  chkHDF5err(H5Aclose(attribute));
  chkHDF5err(H5Gclose(group));

  // close the target file
  chkHDF5err(H5Fclose(target));

  dtime *= factor;
  return (dtime);
}
int
avtGOTHIC_snpFileFormat::GetCycle(void)
{
  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

  // read current time contained in the file (written as an attribute)
  ulong steps;
  hid_t group = H5Gopen(target, "snp", H5P_DEFAULT);
  hid_t attribute = H5Aopen(group, "steps", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_ULONG, &steps));
  chkHDF5err(H5Aclose(attribute));
  chkHDF5err(H5Gclose(group));

  // close the target file
  chkHDF5err(H5Fclose(target));

  int ret = (int)steps;
  return (ret);
}
