/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtMAGI_dfFileFormat.C                           //
// ************************************************************************* //

#include <avtMAGI_dfFileFormat.h>

#include <string>

#include <vtkDoubleArray.h>
#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>

#include <InvalidVariableException.h>


// to use ostringstream
#include <iostream>

//-------------------------------------------------------------------------
// HDF5 related original routines
//-------------------------------------------------------------------------
#include <hdf5.h>
//-------------------------------------------------------------------------
#define chkHDF5err(err) __chkHDF5err(err, __FILE__, __LINE__)
//-------------------------------------------------------------------------
#define __FPRINTF__(dst, ...)				\
  {								\
    fprintf(dst, "%s(%d): %s\n", __FILE__, __LINE__, __func__);	\
    fprintf(dst, ##__VA_ARGS__);				\
    fflush(NULL);						\
  }
//-------------------------------------------------------------------------
#if defined(MPI_INCLUDED) || defined(OMPI_MPI_H)
#     define __KILL__(dst, ...)		\
  {						\
    __FPRINTF__(dst, ##__VA_ARGS__);		\
    MPI_Abort(MPI_COMM_WORLD, 1);		\
  }
#else
#     define __KILL__(dst, ...)		\
  {						\
    __FPRINTF__(dst, ##__VA_ARGS__);		\
    exit(EXIT_FAILURE);				\
  }
#endif
//-------------------------------------------------------------------------
void __chkHDF5err(herr_t err, const char *file, const int line)
{
  //-----------------------------------------------------------------------
  /* Returns a non-negative value if successful; otherwise returns a negative value. */
  if( err < 0 ){
    fprintf(stderr, "Error is detected at %s(%d)\n", file, line);
    __KILL__(stderr, "HDF5 error, error ID is %d\n", err);
  }/* if( err < 0 ){ */
  //-----------------------------------------------------------------------
}
//-------------------------------------------------------------------------



using     std::string;


// ****************************************************************************
//  Method: avtMAGI_dfFileFormat constructor
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Tue Jan 26 16:44:20 PST 2016
//
// ****************************************************************************

avtMAGI_dfFileFormat::avtMAGI_dfFileFormat(const char *filename)
    : avtSTSDFileFormat(filename)
{
    // INITIALIZE DATA MEMBERS
}


// ****************************************************************************
//  Method: avtMAGI_dfFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Tue Jan 26 16:44:20 PST 2016
//
// ****************************************************************************

void
avtMAGI_dfFileFormat::FreeUpResources(void)
{
}


// ****************************************************************************
//  Method: avtMAGI_dfFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Tue Jan 26 16:44:20 PST 2016
//
// ****************************************************************************

void
avtMAGI_dfFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);
  // read number of data groups contained in the file (written as an attribute)
  int kind;
  hid_t attribute = H5Aopen(target, "kinds", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &kind));
  chkHDF5err(H5Aclose(attribute));
  hid_t str4format = H5Tcopy(H5T_C_S1);
  const int charSize = 16;
  chkHDF5err(H5Tset_size(str4format, charSize));
  char senergy_unit[charSize];
  attribute = H5Aopen(target,  "senergy_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,  senergy_unit));  chkHDF5err(H5Aclose(attribute));
  chkHDF5err(H5Tclose(str4format));
  // close the target file
  chkHDF5err(H5Fclose(target));


  for(int ii = 0; ii < kind; ii++){
    // set subgroup
    std::ostringstream oss;
    oss << "series" << ii;
    string meshname = oss.str();

    // add rectilinear mesh
    avtMeshMetaData *mmd = new avtMeshMetaData;
    mmd->name = meshname;
    mmd->spatialDimension = 1;
    mmd->topologicalDimension = 1;
    mmd->meshType = AVT_RECTILINEAR_MESH;
    mmd->numBlocks = 1;  // <-- this must be 1 for STSD
    mmd->xLabel = "Relative energy";    mmd->xUnits = senergy_unit;
    md->Add(mmd);

    // add physical variable
    std::ostringstream var;
    // add scalar variables
    avtScalarMetaData *df = new avtScalarMetaData;    df->meshName = meshname;    df->centering = AVT_NODECENT;    df->hasUnits = false;
    var << meshname << "/DF";    df->name = var.str();    md->Add(df);    var.str("");
  }// for(int ii = 0; ii < kind; ii++){
}


// ****************************************************************************
//  Method: avtMAGI_dfFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Tue Jan 26 16:44:20 PST 2016
//
// ****************************************************************************

vtkDataSet *
avtMAGI_dfFileFormat::GetMesh(const char *meshname)
{
  if( strncmp("series", meshname, 6) == 0 ){
    // open the target file
    const char* filename = GetFilename();
    hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

    // read useDP
    int useDP;
    hid_t attribute = H5Aopen(target, "useDP", H5P_DEFAULT);
    chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &useDP));
    chkHDF5err(H5Aclose(attribute));

    const int ndims = 1;
    int dims[3] = {1, 1, 1};
    // read number of nodes from the file (written as an attribute)
    hid_t group = H5Gopen(target, meshname, H5P_DEFAULT);
    attribute = H5Aopen(group, "num", H5P_DEFAULT);
    chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &dims[0]));
    chkHDF5err(H5Aclose(attribute));

    if( useDP == 0 ){
      vtkFloatArray *coords[3] = {0, 0, 0};
      // read the X coordinates from the file
      coords[0] = vtkFloatArray::New();
      coords[0]->SetNumberOfTuples(dims[0]);
      float *ene = (float *)coords[0]->GetVoidPointer(0);
      hid_t dataset = H5Dopen(group, "energy", H5P_DEFAULT);
      chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, ene));
      chkHDF5err(H5Dclose(dataset));

      // disable the Y coordinates
      coords[1] = vtkFloatArray::New();
      coords[1]->SetNumberOfTuples(1);
      coords[1]->SetComponent(0, 0, 0.);

      // disable the Z coordinates
      coords[2] = vtkFloatArray::New();
      coords[2]->SetNumberOfTuples(1);
      coords[2]->SetComponent(0, 0, 0.);

      // close the target file
      chkHDF5err(H5Gclose(group));
      chkHDF5err(H5Fclose(target));

      // create the vtkRectilinearGrid object and set its dimensions and coordinates
      vtkRectilinearGrid *rgrid = vtkRectilinearGrid::New();
      rgrid->SetDimensions(dims);
      rgrid->SetXCoordinates(coords[0]);    coords[0]->Delete();
      rgrid->SetYCoordinates(coords[1]);    coords[1]->Delete();
      rgrid->SetZCoordinates(coords[2]);    coords[2]->Delete();

      return rgrid;
    }// if( useDP == 0 ){
    else{
      vtkDoubleArray *coords[3] = {0, 0, 0};
      // read the X coordinates from the file
      coords[0] = vtkDoubleArray::New();
      coords[0]->SetNumberOfTuples(dims[0]);
      double *ene = (double *)coords[0]->GetVoidPointer(0);
      hid_t dataset = H5Dopen(group, "energy", H5P_DEFAULT);
      chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, ene));
      chkHDF5err(H5Dclose(dataset));

      // disable the Y coordinates
      coords[1] = vtkDoubleArray::New();
      coords[1]->SetNumberOfTuples(1);
      coords[1]->SetComponent(0, 0, 0.);

      // disable the Z coordinates
      coords[2] = vtkDoubleArray::New();
      coords[2]->SetNumberOfTuples(1);
      coords[2]->SetComponent(0, 0, 0.);

      // close the target file
      chkHDF5err(H5Gclose(group));
      chkHDF5err(H5Fclose(target));

      // create the vtkRectilinearGrid object and set its dimensions and coordinates
      vtkRectilinearGrid *rgrid = vtkRectilinearGrid::New();
      rgrid->SetDimensions(dims);
      rgrid->SetXCoordinates(coords[0]);    coords[0]->Delete();
      rgrid->SetYCoordinates(coords[1]);    coords[1]->Delete();
      rgrid->SetZCoordinates(coords[2]);    coords[2]->Delete();

      return rgrid;
    }// else{
  }// if( strncmp("series", meshname, 6) == 0 ){
  else{
    // Error exception
    EXCEPTION1(InvalidVariableException, meshname);
  }// else{
}


// ****************************************************************************
//  Method: avtMAGI_dfFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Tue Jan 26 16:44:20 PST 2016
//
// ****************************************************************************

vtkDataArray *
avtMAGI_dfFileFormat::GetVar(const char *varname)
{
  // extract meshname and variable from varname (varname = meshname/variable)
  const string str = varname;
  string::size_type pos = str.find_last_of("/");
  string meshname = str.substr(0, pos);
  string variable = str.substr(pos + 1, str.size() - pos);

  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

  // read useDP
  int useDP;
  hid_t attribute = H5Aopen(target, "useDP", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &useDP));
  chkHDF5err(H5Aclose(attribute));

  // read number of particles from the file (written as an attribute)
  int num;
  hid_t group = H5Gopen(target, meshname.c_str(), H5P_DEFAULT);
  attribute = H5Aopen(group, "num", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &num));
  chkHDF5err(H5Aclose(attribute));

  if( useDP == 0 ){
    // read the target variable
    float *array = new float[num];
    hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, array));
    chkHDF5err(H5Dclose(dataset));

    // close the target file
    chkHDF5err(H5Gclose(group));
    chkHDF5err(H5Fclose(target));

    vtkFloatArray *rv = vtkFloatArray::New();
    rv->SetNumberOfTuples(num);
    for(int ii = 0; ii < num; ii++)
      rv->SetTuple1(ii, array[ii]);

    // delete temporary arrays
    delete [] array;

    return rv;
  }// if( useDP == 0 ){
  else{
    // read the target variable
    double *array = new double[num];
    hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, array));
    chkHDF5err(H5Dclose(dataset));

    // close the target file
    chkHDF5err(H5Gclose(group));
    chkHDF5err(H5Fclose(target));

    vtkDoubleArray *rv = vtkDoubleArray::New();
    rv->SetNumberOfTuples(num);
    for(int ii = 0; ii < num; ii++)
      rv->SetTuple1(ii, array[ii]);

    // delete temporary arrays
    delete [] array;

    return rv;
  }// else{
}


// ****************************************************************************
//  Method: avtMAGI_dfFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Tue Jan 26 16:44:20 PST 2016
//
// ****************************************************************************

vtkDataArray *
avtMAGI_dfFileFormat::GetVectorVar(const char *varname)
{
  return (0);
}
