/*****************************************************************************
*
* Copyright (c) 2000 - 2017, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtGOTHIC_pltFileFormat.C                           //
// ************************************************************************* //

#include <avtGOTHIC_pltFileFormat.h>

#include <string>

#include <vtkCellType.h>
#include <vtkUnsignedLongArray.h>
#include <vtkDoubleArray.h>
#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>

#include <InvalidVariableException.h>

// to use ostringstream
#include <iostream>

// HDF5 related original routines
#include <hdf5.h>
#define chkHDF5err(err) __chkHDF5err(err, __FILE__, __LINE__)
#define __FPRINTF__(dst, ...)				\
  {								\
    fprintf(dst, "%s(%d): %s\n", __FILE__, __LINE__, __func__);	\
    fprintf(dst, ##__VA_ARGS__);				\
    fflush(NULL);						\
  }
#if defined(MPI_INCLUDED) || defined(OMPI_MPI_H)
#     define __KILL__(dst, ...)		\
  {						\
    __FPRINTF__(dst, ##__VA_ARGS__);		\
    MPI_Abort(MPI_COMM_WORLD, 1);		\
  }
#else
#     define __KILL__(dst, ...)		\
  {						\
    __FPRINTF__(dst, ##__VA_ARGS__);		\
    exit(EXIT_FAILURE);				\
  }
#endif

void __chkHDF5err(herr_t err, const char *file, const int line)
{
  /* Returns a non-negative value if successful; otherwise returns a negative value. */
  if( err < 0 ){
    fprintf(stderr, "Error is detected at %s(%d)\n", file, line);
    __KILL__(stderr, "HDF5 error, error ID is %d\n", err);
  }/* if( err < 0 ){ */
}
#define INDEX3D(nx, ny, nz, ii, jj, kk) ((kk) + (nz) * ((jj) + (ny) * (ii)))
// typedef unsigned long int ulong;


using     std::string;


// ****************************************************************************
//  Method: avtGOTHIC_pltFileFormat constructor
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Fri Mar 9 10:12:54 PDT 2018
//
// ****************************************************************************

avtGOTHIC_pltFileFormat::avtGOTHIC_pltFileFormat(const char *filename)
    : avtSTSDFileFormat(filename)
{
    // INITIALIZE DATA MEMBERS
}


// ****************************************************************************
//  Method: avtGOTHIC_pltFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Fri Mar 9 10:12:54 PDT 2018
//
// ****************************************************************************

void
avtGOTHIC_pltFileFormat::FreeUpResources(void)
{
}


// ****************************************************************************
//  Method: avtGOTHIC_pltFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Fri Mar 9 10:12:54 PDT 2018
//
// ****************************************************************************

void
avtGOTHIC_pltFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);
  // read number of data groups contained in the file (written as an attribute)
  int kind;
  hid_t attribute = H5Aopen(target, "kinds", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &kind));
  chkHDF5err(H5Aclose(attribute));
  // read unit name contained in the file (written as an attribute)
  hid_t str4format = H5Tcopy(H5T_C_S1);
  const int charSize = 16;
  chkHDF5err(H5Tset_size(str4format, charSize));
  char length_unit[charSize], mass_unit[charSize], time_unit[charSize], velocity_unit[charSize], density_unit[charSize], col_density_unit[charSize];
  attribute = H5Aopen(target,      "length_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,      length_unit));  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target,        "mass_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,        mass_unit));  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target,        "time_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,        time_unit));  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target,    "velocity_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,    velocity_unit));  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target,     "density_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format,     density_unit));  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target, "col_density_astro_unit_name", H5P_DEFAULT);  chkHDF5err(H5Aread(attribute, str4format, col_density_unit));  chkHDF5err(H5Aclose(attribute));
  chkHDF5err(H5Tclose(str4format));
  // close the target file
  chkHDF5err(H5Fclose(target));


  for(int ii = 0; ii < kind; ii++){
    // set subgroup
    std::ostringstream oss;
    oss << "field" << ii;
    string meshname = oss.str();

    // add rectlinear mesh
    avtMeshMetaData *mmd = new avtMeshMetaData;
    mmd->name = meshname;
    mmd->spatialDimension = 3;
    mmd->topologicalDimension = 3;
    mmd->meshType = AVT_RECTILINEAR_MESH;
    mmd->numBlocks = 1;  // <-- this must be 1 for STSD
    mmd->xLabel = "x";    mmd->xUnits = length_unit;
    mmd->yLabel = "y";    mmd->yUnits = length_unit;
    mmd->zLabel = "z";    mmd->zUnits = length_unit;
    md->Add(mmd);

    // add physical variables
    std::ostringstream var;
    // add scalar variables
    avtScalarMetaData *rho = new avtScalarMetaData;    rho->meshName = meshname;    rho->centering = AVT_ZONECENT;    rho->hasUnits =  true;
    var << meshname << "/rho";    rho->name = var.str();    rho->units = density_unit;    md->Add(rho);    var.str("");
  }// for(int ii = 0; ii < kind; ii++){
}


// ****************************************************************************
//  Method: avtGOTHIC_pltFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Fri Mar 9 10:12:54 PDT 2018
//
// ****************************************************************************

vtkDataSet *
avtGOTHIC_pltFileFormat::GetMesh(const char *meshname)
{
  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

  // read useDP
  int useDP;
  hid_t attribute = H5Aopen(target, "useDP", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &useDP));
  chkHDF5err(H5Aclose(attribute));

  const int ndims = 3;
  int dims[3] = {1, 1, 1};
  // read number of nodes from the file (written as an attribute)
  attribute = H5Aopen(target, "nx", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &dims[0]));
  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target, "ny", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &dims[1]));
  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target, "nz", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &dims[2]));
  chkHDF5err(H5Aclose(attribute));
  dims[0]++;
  dims[1]++;
  dims[2]++;

  hid_t group = H5Gopen(target, meshname, H5P_DEFAULT);

  if( useDP == 0 ){
    vtkFloatArray *coords[3] = {0, 0, 0};

    // read the X coordinates from the file
    coords[0] = vtkFloatArray::New();
    coords[0]->SetNumberOfTuples(dims[0]);
    float *xx = (float *)coords[0]->GetVoidPointer(0);
    hid_t dataset = H5Dopen(group, "x", H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, xx));
    chkHDF5err(H5Dclose(dataset));

    // read the Y coordinates from the file
    coords[1] = vtkFloatArray::New();
    coords[1]->SetNumberOfTuples(dims[1]);
    float *yy = (float *)coords[1]->GetVoidPointer(0);
    dataset = H5Dopen(group, "y", H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, yy));
    chkHDF5err(H5Dclose(dataset));

    // read the Z coordinates from the file
    coords[2] = vtkFloatArray::New();
    coords[2]->SetNumberOfTuples(dims[2]);
    float *zz = (float *)coords[2]->GetVoidPointer(0);
    dataset = H5Dopen(group, "z", H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, zz));
    chkHDF5err(H5Dclose(dataset));

    // close the target file
    chkHDF5err(H5Gclose(group));
    chkHDF5err(H5Fclose(target));

    // create the vtkRectilinearGrid object and set its dimensions and coordinates
    vtkRectilinearGrid *rgrid = vtkRectilinearGrid::New();
    rgrid->SetDimensions(dims);
    rgrid->SetXCoordinates(coords[0]);
    rgrid->SetYCoordinates(coords[1]);
    rgrid->SetZCoordinates(coords[2]);

    coords[0]->Delete();
    coords[1]->Delete();
    coords[2]->Delete();

    return rgrid;
  }// if( useDP == 0 ){
  else{
    vtkDoubleArray *coords[3] = {0, 0, 0};

    // read the X coordinates from the file
    coords[0] = vtkDoubleArray::New();
    coords[0]->SetNumberOfTuples(dims[0]);
    double *xx = (double *)coords[0]->GetVoidPointer(0);
    hid_t dataset = H5Dopen(group, "x", H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, xx));
    chkHDF5err(H5Dclose(dataset));

    // read the Y coordinates from the file
    coords[1] = vtkDoubleArray::New();
    coords[1]->SetNumberOfTuples(dims[1]);
    double *yy = (double *)coords[1]->GetVoidPointer(0);
    dataset = H5Dopen(group, "y", H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, yy));
    chkHDF5err(H5Dclose(dataset));

    // read the Z coordinates from the file
    coords[2] = vtkDoubleArray::New();
    coords[2]->SetNumberOfTuples(dims[2]);
    double *zz = (double *)coords[2]->GetVoidPointer(0);
    dataset = H5Dopen(group, "z", H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, zz));
    chkHDF5err(H5Dclose(dataset));

    // close the target file
    chkHDF5err(H5Gclose(group));
    chkHDF5err(H5Fclose(target));

    // create the vtkRectilinearGrid object and set its dimensions and coordinates
    vtkRectilinearGrid *rgrid = vtkRectilinearGrid::New();
    rgrid->SetDimensions(dims);
    rgrid->SetXCoordinates(coords[0]);
    rgrid->SetYCoordinates(coords[1]);
    rgrid->SetZCoordinates(coords[2]);

    coords[0]->Delete();
    coords[1]->Delete();
    coords[2]->Delete();

    return rgrid;
  }// else{

  EXCEPTION1(InvalidVariableException, meshname);
}


// ****************************************************************************
//  Method: avtGOTHIC_pltFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Fri Mar 9 10:12:54 PDT 2018
//
// ****************************************************************************

vtkDataArray *
avtGOTHIC_pltFileFormat::GetVar(const char *varname)
{
  // extract meshname and variable from varname (varname = meshname/variable)
  const string str = varname;
  string::size_type pos = str.find_last_of("/");
  string meshname = str.substr(0, pos);
  string variable = str.substr(pos + 1, str.size() - pos);

  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

  // read useDP
  int useDP;
  hid_t attribute = H5Aopen(target, "useDP", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &useDP));
  chkHDF5err(H5Aclose(attribute));

  const int ndims = 3;
  int dims[3] = {1, 1, 1};
  // read number of nodes from the file (written as an attribute)
  attribute = H5Aopen(target, "nx", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &dims[0]));
  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target, "ny", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &dims[1]));
  chkHDF5err(H5Aclose(attribute));
  attribute = H5Aopen(target, "nz", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_INT, &dims[2]));
  chkHDF5err(H5Aclose(attribute));

  hid_t group = H5Gopen(target, meshname.c_str(), H5P_DEFAULT);

  if( useDP == 0 ){
    vtkFloatArray *coords[3] = {0, 0, 0};
    // read the target variable
    float *var = new float[dims[0] * dims[1] * dims[2]];
    hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_FLOAT, H5S_ALL, H5S_ALL, H5P_DEFAULT, var));
    chkHDF5err(H5Dclose(dataset));

    // close the target file
    chkHDF5err(H5Gclose(group));
    chkHDF5err(H5Fclose(target));

    vtkFloatArray *rv = vtkFloatArray::New();
    rv->SetNumberOfTuples(dims[0] * dims[1] * dims[2]);
    for(int ii = 0; ii < dims[0]; ii++)
      for(int jj = 0; jj < dims[1]; jj++)
	for(int kk = 0; kk < dims[2]; kk++)
	  rv->SetTuple1(INDEX3D(dims[2], dims[1], dims[0], kk, jj, ii), var[INDEX3D(dims[0], dims[1], dims[2], ii, jj, kk)]);
    // rv->SetTuple1(INDEX2D(dims[0], dims[1], ii, jj), ver[INDEX2D(dims[0], dims[1], ii, jj)]);

    // delete temporary arrays
    delete [] var;

    return rv;
  }// if( useDP == 0 ){
  else{
    vtkDoubleArray *coords[3] = {0, 0, 0};
    // read the target variable
    double *var = new double[dims[0] * dims[1] * dims[2]];
    hid_t dataset = H5Dopen(group, variable.c_str(), H5P_DEFAULT);
    chkHDF5err(H5Dread(dataset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, var));
    chkHDF5err(H5Dclose(dataset));

    // close the target file
    chkHDF5err(H5Gclose(group));
    chkHDF5err(H5Fclose(target));

    vtkDoubleArray *rv = vtkDoubleArray::New();
    rv->SetNumberOfTuples(dims[0] * dims[1] * dims[2]);
    for(int ii = 0; ii < dims[0]; ii++)
      for(int jj = 0; jj < dims[1]; jj++)
	for(int kk = 0; kk < dims[2]; kk++)
	  rv->SetTuple1(INDEX3D(dims[2], dims[1], dims[0], kk, jj, ii), var[INDEX3D(dims[0], dims[1], dims[2], ii, jj, kk)]);
    // rv->SetTuple1(INDEX2D(dims[0], dims[1], ii, jj), ver[INDEX2D(dims[0], dims[1], ii, jj)]);

    // delete temporary arrays
    delete [] var;

    return rv;
  }// else{
  EXCEPTION1(InvalidVariableException, varname);
}


// ****************************************************************************
//  Method: avtGOTHIC_pltFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      varname    The name of the variable requested.
//
//  Programmer: ymiki -- generated by xml2avt
//  Creation:   Fri Mar 9 10:12:54 PDT 2018
//
// ****************************************************************************

vtkDataArray *
avtGOTHIC_pltFileFormat::GetVectorVar(const char *varname)
{
  EXCEPTION1(InvalidVariableException, varname);
}


// optional function(s)
double
avtGOTHIC_pltFileFormat::GetTime(void)
{
  // open the target file
  const char* filename = GetFilename();
  hid_t target = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);
  // read current time contained in the file (written as an attribute)
  double dtime;
  hid_t attribute = H5Aopen(target, "time", H5P_DEFAULT);
  chkHDF5err(H5Aread(attribute, H5T_NATIVE_DOUBLE, &dtime));
  chkHDF5err(H5Aclose(attribute));
  // close the target file
  chkHDF5err(H5Fclose(target));

  return (dtime);
}
